/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Joaquin
 */
public class EntornoView extends javax.swing.JFrame {

    /**
     * Creates new form EntornoView
     */
    public EntornoView() {
        initComponents();
    }
    
    public void fillCbGeneraciones(int numOfGenerations){
        System.out.println("+++++++++++++++++++++++ NUM OF GENERATIONS: " + numOfGenerations);
        String[] array = new String[numOfGenerations];
        for(int i = 0; i < array.length; i++) {
            array[i] = "Generación " + Integer.toString(i+1);
        }
        this.cbGeneraciones.setModel(new DefaultComboBoxModel<>(array));
    }
    
    public void fillCbRobots(int numOfRobot){
        String[] array = new String[numOfRobot];
        for(int i = 0; i < array.length; i++) {
            array[i] = "Robot " + Integer.toString(i+1);
        }
        this.cbRobots.setModel(new DefaultComboBoxModel<>(array));
    }
    
    public void fillCbExitosos(ArrayList<Integer> exitososGeneraciones){
        String[] array = new String[exitososGeneraciones.size()];
        for(int i = 0; i < array.length; i++) {
            array[i] = "Generación " + Integer.toString(i+1) + " fueron exitosos: " + exitososGeneraciones.get(i);
        }
        this.cbExitososPorGeneracion.setModel(new DefaultComboBoxModel<>(array));
    }
    
    public void fillCbMutaciones(ArrayList<Integer> mutacionesGeneraciones){
        String[] array = new String[mutacionesGeneraciones.size()];
        for(int i = 0; i < array.length; i++) {
            array[i] = "Generación " + Integer.toString(i+1) + " fueron mutados: " + mutacionesGeneraciones.get(i);
        }
        this.cbMutacionesPorGeneracion.setModel(new DefaultComboBoxModel<>(array));        
    }
    
    
    public void _init_components(int numOfGenerations, int numOfRobots, ArrayList<Integer> exitososGeneraciones, ArrayList<Integer> mutacionesGeneraciones){
        fillCbGeneraciones(numOfGenerations);
        fillCbRobots(numOfRobots);
        fillCbExitosos(exitososGeneraciones);
        fillCbMutaciones(mutacionesGeneraciones);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbGeneraciones = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cbRobots = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnBuscarRobot = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cbExitososPorGeneracion = new javax.swing.JComboBox<>();
        btnExitososEnGeneracion = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cbMutacionesPorGeneracion = new javax.swing.JComboBox<>();
        btnMutacionesPorGeneracion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(475, 375));
        getContentPane().setLayout(null);

        cbGeneraciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbGeneraciones);
        cbGeneraciones.setBounds(26, 55, 132, 28);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Generación");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(26, 35, 132, 14);

        cbRobots.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbRobots);
        cbRobots.setBounds(168, 55, 132, 28);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Robot");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(168, 35, 132, 14);

        btnBuscarRobot.setText("Buscar");
        btnBuscarRobot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarRobotActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscarRobot);
        btnBuscarRobot.setBounds(322, 58, 85, 23);

        jLabel3.setText("Exitosos por generación");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(88, 132, 115, 14);

        cbExitososPorGeneracion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbExitososPorGeneracion);
        cbExitososPorGeneracion.setBounds(26, 152, 278, 29);

        btnExitososEnGeneracion.setText("Especificos");
        getContentPane().add(btnExitososEnGeneracion);
        btnExitososEnGeneracion.setBounds(322, 155, 85, 23);

        jLabel4.setText("Mutaciones por generación");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(93, 240, 129, 14);

        cbMutacionesPorGeneracion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbMutacionesPorGeneracion);
        cbMutacionesPorGeneracion.setBounds(26, 260, 274, 29);

        btnMutacionesPorGeneracion.setText("Especificos");
        getContentPane().add(btnMutacionesPorGeneracion);
        btnMutacionesPorGeneracion.setBounds(322, 263, 85, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarRobotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarRobotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarRobotActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntornoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntornoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntornoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntornoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntornoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscarRobot;
    public javax.swing.JButton btnExitososEnGeneracion;
    public javax.swing.JButton btnMutacionesPorGeneracion;
    public javax.swing.JComboBox<String> cbExitososPorGeneracion;
    public javax.swing.JComboBox<String> cbGeneraciones;
    public javax.swing.JComboBox<String> cbMutacionesPorGeneracion;
    public javax.swing.JComboBox<String> cbRobots;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
