/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Robot;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Joaquin
 */
public class RobotInfo extends javax.swing.JFrame {
    public final int CANT_ESPACIOS = 20;
    public final int WIDTH_CUAD = 35;
    public final int HEIGHT_CUAD = 35;
    public JButton myTablero[][] = new JButton[CANT_ESPACIOS][CANT_ESPACIOS];
    
    
    public void setTextFieldsEditableFalse(){
        this.tfAdaptabilidad.setEditable(false);
        this.tfCargaBateria.setEditable(false);
        this.tfConsumoCamara.setEditable(false);
        this.tfConsumoMotor.setEditable(false);
        this.tfCostoBateria.setEditable(false);
        this.tfCostoCamara.setEditable(false);
        this.tfCostoMotor.setEditable(false);
        this.tfExitoso.setEditable(false);
        this.tfGeneracion.setEditable(false);
        this.tfModeloBateria.setEditable(false);
        this.tfModeloCamara.setEditable(false);
        this.tfModeloMotor.setEditable(false);
        this.tfNumeroRobot.setEditable(false);
    }
    
    public void setTextFieldsInfo(Robot robot, int numGen, int numRobot){
        this.tfAdaptabilidad.setText(Integer.toString(robot.getActualAdaptabilidad()));
        this.tfCargaBateria.setText(Integer.toString(robot.bateria.getCarga()));
        this.tfConsumoCamara.setText(Integer.toString(robot.camara.getConsumo()));
        this.tfConsumoMotor.setText(Integer.toString(robot.motor.getConsumo()));
        this.tfCostoBateria.setText(Integer.toString(robot.bateria.getCosto()));
        this.tfCostoCamara.setText(Integer.toString(robot.camara.getCosto()));
        this.tfCostoMotor.setText(Integer.toString(robot.motor.getCosto()));
        this.tfExitoso.setText(Boolean.toString(robot.exitoso));
        this.tfGeneracion.setText(Integer.toString(numGen));
        this.tfModeloBateria.setText(Integer.toString(robot.bateria.getTipo()));
        this.tfModeloMotor.setText(Integer.toString(robot.motor.getTipo()));
        this.tfModeloCamara.setText(Integer.toString(robot.camara.getTipo()));
        this.tfNumeroRobot.setText(Integer.toString(numRobot));
    }
    
    public void _init_components(Robot robot, int numGen, int numRobot){
        setTextFieldsEditableFalse();
        setTextFieldsInfo(robot, numGen, numRobot);
    }
    
    
    /**
     * Creates new form RobotInfo
     */
    public RobotInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelTerreno = new javax.swing.JPanel();
        labelMotor = new javax.swing.JLabel();
        labelCamara = new javax.swing.JLabel();
        labelBateria = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfModeloBateria = new javax.swing.JTextField();
        tfCostoBateria = new javax.swing.JTextField();
        tfCargaBateria = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfModeloCamara = new javax.swing.JTextField();
        tfCostoCamara = new javax.swing.JTextField();
        tfConsumoCamara = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tfModeloMotor = new javax.swing.JTextField();
        tfCostoMotor = new javax.swing.JTextField();
        tfConsumoMotor = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tfGeneracion = new javax.swing.JTextField();
        tfNumeroRobot = new javax.swing.JTextField();
        tfAdaptabilidad = new javax.swing.JTextField();
        tfExitoso = new javax.swing.JTextField();
        btnAntepasado1 = new javax.swing.JButton();
        btnAntepasado2 = new javax.swing.JButton();
        panelHardwareGenes = new javax.swing.JPanel();
        panelMovementGenes = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1152, 890));
        getContentPane().setLayout(null);

        panelTerreno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelTerreno.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(panelTerreno);
        panelTerreno.setBounds(19, 37, 2, 2);

        labelMotor.setText("Motor");
        labelMotor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(labelMotor);
        labelMotor.setBounds(639, 270, 95, 103);

        labelCamara.setText("Bateria");
        labelCamara.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(labelCamara);
        labelCamara.setBounds(639, 48, 95, 96);

        labelBateria.setText("Camara");
        labelBateria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(labelBateria);
        labelBateria.setBounds(639, 159, 95, 96);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel4.setText("Modelo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 11, 0, 0);
        jPanel2.add(jLabel4, gridBagConstraints);

        jLabel5.setText("Costo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 11, 0, 0);
        jPanel2.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Carga:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 11, 0, 0);
        jPanel2.add(jLabel6, gridBagConstraints);

        tfModeloBateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfModeloBateriaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 4, 0, 0);
        jPanel2.add(tfModeloBateria, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 4, 0, 0);
        jPanel2.add(tfCostoBateria, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 5, 12, 20);
        jPanel2.add(tfCargaBateria, gridBagConstraints);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(752, 48, 133, 98);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel7.setText("Modelo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 11, 0, 0);
        jPanel3.add(jLabel7, gridBagConstraints);

        jLabel8.setText("Costo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 11, 0, 0);
        jPanel3.add(jLabel8, gridBagConstraints);

        jLabel9.setText("Consumo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 11, 0, 0);
        jPanel3.add(jLabel9, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 4, 0, 11);
        jPanel3.add(tfModeloCamara, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 4, 0, 11);
        jPanel3.add(tfCostoCamara, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 4, 12, 11);
        jPanel3.add(tfConsumoCamara, gridBagConstraints);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(752, 159, 130, 98);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel10.setText("Modelo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 11, 0, 0);
        jPanel4.add(jLabel10, gridBagConstraints);

        jLabel11.setText("Costo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 11, 0, 0);
        jPanel4.add(jLabel11, gridBagConstraints);

        jLabel12.setText("Consumo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 11, 0, 0);
        jPanel4.add(jLabel12, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 4, 0, 11);
        jPanel4.add(tfModeloMotor, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 4, 0, 11);
        jPanel4.add(tfCostoMotor, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 4, 19, 11);
        jPanel4.add(tfConsumoMotor, gridBagConstraints);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(752, 270, 130, 105);

        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel13.setText("Robot");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 12, 0, 0);
        jPanel5.add(jLabel13, gridBagConstraints);

        jLabel14.setText("Generación:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 53, 0, 0);
        jPanel5.add(jLabel14, gridBagConstraints);

        jLabel15.setText("Número:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 53, 0, 0);
        jPanel5.add(jLabel15, gridBagConstraints);

        jLabel16.setText("Adaptabilidad:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 53, 0, 0);
        jPanel5.add(jLabel16, gridBagConstraints);

        jLabel17.setText("Exitoso:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 53, 0, 0);
        jPanel5.add(jLabel17, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 59;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 4, 0, 55);
        jPanel5.add(tfGeneracion, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 59;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 4, 0, 55);
        jPanel5.add(tfNumeroRobot, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 59;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 4, 0, 55);
        jPanel5.add(tfAdaptabilidad, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 59;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 4, 11, 55);
        jPanel5.add(tfExitoso, gridBagConstraints);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(639, 391, 246, 140);

        btnAntepasado1.setText("Antepasado 1");
        btnAntepasado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAntepasado1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAntepasado1);
        btnAntepasado1.setBounds(639, 549, 120, 60);

        btnAntepasado2.setText("Antepasado 2");
        getContentPane().add(btnAntepasado2);
        btnAntepasado2.setBounds(765, 549, 120, 60);

        panelHardwareGenes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelHardwareGenes.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(panelHardwareGenes);
        panelHardwareGenes.setBounds(960, 50, 40, 450);

        panelMovementGenes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelMovementGenes.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(panelMovementGenes);
        panelMovementGenes.setBounds(1040, 10, 40, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAntepasado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAntepasado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAntepasado1ActionPerformed

    private void tfModeloBateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfModeloBateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfModeloBateriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RobotInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RobotInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RobotInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RobotInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RobotInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAntepasado1;
    private javax.swing.JButton btnAntepasado2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel labelBateria;
    private javax.swing.JLabel labelCamara;
    private javax.swing.JLabel labelMotor;
    public javax.swing.JPanel panelHardwareGenes;
    public javax.swing.JPanel panelMovementGenes;
    public javax.swing.JPanel panelTerreno;
    private javax.swing.JTextField tfAdaptabilidad;
    private javax.swing.JTextField tfCargaBateria;
    private javax.swing.JTextField tfConsumoCamara;
    private javax.swing.JTextField tfConsumoMotor;
    private javax.swing.JTextField tfCostoBateria;
    private javax.swing.JTextField tfCostoCamara;
    private javax.swing.JTextField tfCostoMotor;
    private javax.swing.JTextField tfExitoso;
    private javax.swing.JTextField tfGeneracion;
    private javax.swing.JTextField tfModeloBateria;
    private javax.swing.JTextField tfModeloCamara;
    private javax.swing.JTextField tfModeloMotor;
    private javax.swing.JTextField tfNumeroRobot;
    // End of variables declaration//GEN-END:variables
}
